include current-theme.conf
map super+q close_window
window_padding_width 5
placement_strategy top-left
font_family Iosevka Nerd Font
font_size 19.0
cursor_shape beam
cursor_shape_unfocused beam
background_opacity 0.75
background_blur 1
